# Generated by Django 5.2.17 on 2026-09-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='media'),
        ),
    ]
