# Generated by Django 5.2.17 on 2026-09-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andet', '0003_post_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='media'),
        ),
    ]
